### ISSUE TITLE
Can't pickle local object 'DoubleBufferedIterator._

### ISSUE THREAD

**Issue by WJ-8** [HuantWang/FUNDED_NISL#11]
I met a problem: `Can't pickle local object 'DoubleBufferedIterator._`
env:`cuda`10.0 `cudnn`7.4.1 `GPU`RTX 3090 x1
# console output
```
2022-03-27 11:30:04.495748: W tensorflow/core/framework/op_kernel.cc:1610] Unknown: AttributeError: Can't pickle local object 'DoubleBufferedIterator.__init__.<locals>.<lambda>'
Traceback (most recent call last):

  File "D:\ProgramData\Anaconda3\envs\funded\lib\site-packages\tensorflow_core\python\data\ops\dataset_ops.py", line 464, in get_iterator
    return self._iterators[iterator_id]

KeyError: 0


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "D:\ProgramData\Anaconda3\envs\funded\lib\site-packages\tensorflow_core\python\ops\script_ops.py", line 221, in __call__
    ret = func(*args)

  File "D:\ProgramData\Anaconda3\envs\funded\lib\site-packages\tensorflow_core\python\data\ops\dataset_ops.py", line 585, in generator_py_func
    values = next(generator_state.get_iterator(iterator_id))

  File "D:\ProgramData\Anaconda3\envs\funded\lib\site-packages\tensorflow_core\python\data\ops\dataset_ops.py", line 466, in get_iterator
    iterator = iter(self._generator(*self._args.pop(iterator_id)))

  File "E:\FUNDED\FUNDED\data\graph_dataset.py", line 216, in <lambda>
    self.graph_batch_iterator(data_fold)

  File "D:\ProgramData\Anaconda3\envs\funded\lib\site-packages\dpu_utils\utils\iterators.py", line 148, in __init__
    self.__worker_process_inner.start()

  File "D:\ProgramData\Anaconda3\envs\funded\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)

  File "D:\ProgramData\Anaconda3\envs\funded\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)

  File "D:\ProgramData\Anaconda3\envs\funded\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)

  File "D:\ProgramData\Anaconda3\envs\funded\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)

  File "D:\ProgramData\Anaconda3\envs\funded\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)

AttributeError: Can't pickle local object 'DoubleBufferedIterator.__init__.<locals>.<lambda>'


2022-03-27 11:30:04.496721: W tensorflow/core/framework/op_kernel.cc:1622] OP_REQUIRES failed at iterator_ops.cc:929 : Unknown: AttributeError: Can't pickle local object 'DoubleBufferedIterator.__init__.<locals>.<lambda>'
Traceback (most recent call last):

  File "D:\ProgramData\Anaconda3\envs\funded\lib\site-packages\tensorflow_core\python\data\ops\dataset_ops.py", line 464, in get_iterator
    return self._iterators[iterator_id]

KeyError: 0


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "D:\ProgramData\Anaconda3\envs\funded\lib\site-packages\tensorflow_core\python\ops\script_ops.py", line 221, in __call__
    ret = func(*args)

  File "D:\ProgramData\Anaconda3\envs\funded\lib\site-packages\tensorflow_core\python\data\ops\dataset_ops.py", line 585, in generator_py_func
    values = next(generator_state.get_iterator(iterator_id))

  File "D:\ProgramData\Anaconda3\envs\funded\lib\site-packages\tensorflow_core\python\data\ops\dataset_ops.py", line 466, in get_iterator
    iterator = iter(self._generator(*self._args.pop(iterator_id)))

  File "E:\FUNDED\FUNDED\data\graph_dataset.py", line 216, in <lambda>
    self.graph_batch_iterator(data_fold)

  File "D:\ProgramData\Anaconda3\envs\funded\lib\site-packages\dpu_utils\utils\iterators.py", line 148, in __init__
    self.__worker_process_inner.start()

  File "D:\ProgramData\Anaconda3\envs\funded\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)

  File "D:\ProgramData\Anaconda3\envs\funded\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)

  File "D:\ProgramData\Anaconda3\envs\funded\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)

  File "D:\ProgramData\Anaconda3\envs\funded\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)

  File "D:\ProgramData\Anaconda3\envs\funded\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)

AttributeError: Can't pickle local object 'DoubleBufferedIterator.__init__.<locals>.<lambda>'


         [[{{node PyFunc}}]]
2022-03-27 11:30:04.497356: W tensorflow/core/framework/op_kernel.cc:1610] Unknown: KeyError: 0
Traceback (most recent call last):

  File "D:\ProgramData\Anaconda3\envs\funded\lib\site-packages\tensorflow_core\python\data\ops\dataset_ops.py", line 464, in get_iterator
    return self._iterators[iterator_id]

KeyError: 0


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "D:\ProgramData\Anaconda3\envs\funded\lib\site-packages\tensorflow_core\python\ops\script_ops.py", line 221, in __call__
    ret = func(*args)

  File "D:\ProgramData\Anaconda3\envs\funded\lib\site-packages\tensorflow_core\python\data\ops\dataset_ops.py", line 585, in generator_py_func
    values = next(generator_state.get_iterator(iterator_id))

  File "D:\ProgramData\Anaconda3\envs\funded\lib\site-packages\tensorflow_core\python\data\ops\dataset_ops.py", line 466, in get_iterator
    iterator = iter(self._generator(*self._args.pop(iterator_id)))

KeyError: 0


Traceback (most recent call last):
  File "train.py", line 62, in <module>
    run()
  File "train.py", line 37, in run
2022-03-27 11:30:04.502260: W tensorflow/core/framework/op_kernel.cc:1610] Unknown: KeyError: 0
Traceback (most recent call last):

  File "D:\ProgramData\Anaconda3\envs\funded\lib\site-packages\tensorflow_core\python\data\ops\dataset_ops.py", line 464, in get_iterator
    return self._iterators[iterator_id]

KeyError: 0


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "D:\ProgramData\Anaconda3\envs\funded\lib\site-packages\tensorflow_core\python\ops\script_ops.py", line 221, in __call__
    ret = func(*args)

  File "D:\ProgramData\Anaconda3\envs\funded\lib\site-packages\tensorflow_core\python\data\ops\dataset_ops.py", line 585, in generator_py_func
    values = next(generator_state.get_iterator(iterator_id))

  File "D:\ProgramData\Anaconda3\envs\funded\lib\site-packages\tensorflow_core\python\data\ops\dataset_ops.py", line 466, in get_iterator
    iterator = iter(self._generator(*self._args.pop(iterator_id)))

KeyError: 0


    lambda: run_train_from_args(args, hyperdrive_hyperparameter_overrides), args.debug
  File "D:\ProgramData\Anaconda3\envs\funded\lib\site-packages\dpu_utils\utils\debughelper.py", line 21, in run_and_debug
2022-03-27 11:30:04.503196: W tensorflow/core/framework/op_kernel.cc:1610] Unknown: KeyError: 0
Traceback (most recent call last):

  File "D:\ProgramData\Anaconda3\envs\funded\lib\site-packages\tensorflow_core\python\data\ops\dataset_ops.py", line 464, in get_iterator
    return self._iterators[iterator_id]

KeyError: 0


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "D:\ProgramData\Anaconda3\envs\funded\lib\site-packages\tensorflow_core\python\ops\script_ops.py", line 221, in __call__
    ret = func(*args)

  File "D:\ProgramData\Anaconda3\envs\funded\lib\site-packages\tensorflow_core\python\data\ops\dataset_ops.py", line 585, in generator_py_func
    values = next(generator_state.get_iterator(iterator_id))

  File "D:\ProgramData\Anaconda3\envs\funded\lib\site-packages\tensorflow_core\python\data\ops\dataset_ops.py", line 466, in get_iterator
    iterator = iter(self._generator(*self._args.pop(iterator_id)))

KeyError: 0


    func()
  File "train.py", line 37, in <lambda>
    lambda: run_train_from_args(args, hyperdrive_hyperparameter_overrides), args.debug
  File "E:\FUNDED\FUNDED\cli_utils\training_utils.py", line 219, in run_train_from_args
    aml_run=aml_run,
  File "E:\FUNDED\FUNDED\cli_utils\training_utils.py", line 59, in train
    _, _, initial_valid_results = model.run_one_epoch_new(train_data,train_data_2, training=False, quiet=quiet)
  File "E:\FUNDED\FUNDED\models\graph_task_model.py", line 318, in run_one_epoch_new
    for ((step, (batch_features, batch_labels)),(step_2, (batch_features_2, batch_labels_2))) in zip(enumerate(dataset),enumerate(dataset2)):
  File "D:\ProgramData\Anaconda3\envs\funded\lib\site-packages\tensorflow_core\python\data\ops\iterator_ops.py", line 622, in __next__
    return self.next()
  File "D:\ProgramData\Anaconda3\envs\funded\lib\site-packages\tensorflow_core\python\data\ops\iterator_ops.py", line 666, in next
    return self._next_internal()
  File "D:\ProgramData\Anaconda3\envs\funded\lib\site-packages\tensorflow_core\python\data\ops\iterator_ops.py", line 651, in _next_internal
    output_shapes=self._flat_output_shapes)
  File "D:\ProgramData\Anaconda3\envs\funded\lib\site-packages\tensorflow_core\python\ops\gen_dataset_ops.py", line 2673, in iterator_get_next_sync
    _six.raise_from(_core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.UnknownError: AttributeError: Can't pickle local object 'DoubleBufferedIterator.__init__.<locals>.<lambda>'
Traceback (most recent call last):

  File "D:\ProgramData\Anaconda3\envs\funded\lib\site-packages\tensorflow_core\python\data\ops\dataset_ops.py", line 464, in get_iterator
    return self._iterators[iterator_id]

KeyError: 0


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "D:\ProgramData\Anaconda3\envs\funded\lib\site-packages\tensorflow_core\python\ops\script_ops.py", line 221, in __call__
    ret = func(*args)

  File "D:\ProgramData\Anaconda3\envs\funded\lib\site-packages\tensorflow_core\python\data\ops\dataset_ops.py", line 585, in generator_py_func
    values = next(generator_state.get_iterator(iterator_id))

  File "D:\ProgramData\Anaconda3\envs\funded\lib\site-packages\tensorflow_core\python\data\ops\dataset_ops.py", line 466, in get_iterator
    iterator = iter(self._generator(*self._args.pop(iterator_id)))

  File "E:\FUNDED\FUNDED\data\graph_dataset.py", line 216, in <lambda>
    self.graph_batch_iterator(data_fold)

  File "D:\ProgramData\Anaconda3\envs\funded\lib\site-packages\dpu_utils\utils\iterators.py", line 148, in __init__
    self.__worker_process_inner.start()

  File "D:\ProgramData\Anaconda3\envs\funded\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)

  File "D:\ProgramData\Anaconda3\envs\funded\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)

  File "D:\ProgramData\Anaconda3\envs\funded\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)

  File "D:\ProgramData\Anaconda3\envs\funded\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)

  File "D:\ProgramData\Anaconda3\envs\funded\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)

AttributeError: Can't pickle local object 'DoubleBufferedIterator.__init__.<locals>.<lambda>'


         [[{{node PyFunc}}]] [Op:IteratorGetNextSync]
2022-03-27 11:30:05.779555: W tensorflow/core/kernels/data/generator_dataset_op.cc:102] Error occurred when finalizing GeneratorDataset iterator: Failed precondition: Python interpreter state is not initialized. The process may be terminated.
         [[{{node PyFunc}}]]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\ProgramData\Anaconda3\envs\funded\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "D:\ProgramData\Anaconda3\envs\funded\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input
```

**Comment by HuantWang** [comment]
I found this seems like a known issue about lambda functions. 
Please retry with `num_worksers=0`, and let me know if this solves the problem.

**Comment by WJ-8** [comment]
Thanks for your reply.I think it was a problem about cuda version.when i used pytorch-cpu,i fixed the bug.

**Comment by HuantWang** [comment]
> Thanks for your reply.I think it was a problem about cuda version.when i used pytorch-cpu,i fixed the bug.

That's great! : )
